#!/bin/bash
#Adds bash aliases or "shortcuts"

cd ~/
readarray install < programs.txt

if echo "${install[1]}" | grep -iq "^y" ;then
    echo 'alias spotify="sudo enter-chroot -b xiwi -T spotify"' >> .bashrc
fi
if echo "${install[2]}" | grep -iq "^y" ;then
    echo 'alias skype="sudo enter-chroot -b xiwi -T skype"' >> .bashrc
fi
if echo "${install[3]}" | grep -iq "^y" ;then
    echo 'alias steam="sudo iptables-restore < ~/iptables.rules; sudo enter-chroot -b xiwi -F steam"' >> .bashrc
fi
if echo "${install[4]}" | grep -iq "^y" ;then
    echo 'alias vlc="sudo enter-chroot -b xiwi -F vlc"' >> .bashrc
fi
if echo "${install[5]}" | grep -iq "^y" ;then
    echo 'alias arduino="sudo enter-chroot -b xiwi -T arduino"' >> .bashrc
fi
echo 'alias term="sudo enter-chroot"' >> .bashrc
echo 'alias on="sudo start powerd"' >> .bashrc
echo 'alias off="sudo enter-chroot brightness 0%; sudo stop powerd"' >> .bashrc
echo 'alias root="cd mnt/stateful_partition/crouton/chroots/trusty"' >> .bashrc
echo 'alias shortcuts="bash ~/Shortcuts"' >> .bashrc
