#!/bin/bash
#Chromebook Script

cd ~/Downloads
wget https://github.com/dnschneid/crouton/raw/master/installer/crouton
sudo sh crouton -r trusty -t xiwi,core

sudo cp LinuxInstall /mnt/stateful_partition/crouton/chroots/trusty/bin

sudo enter-chroot -l sh /bin/LinuxInstall

cp bashrc ~/.bashrc

echo "All Done"; echo""; echo"";

echo "Shortcuts:"
echo "spotify --> Open Spotify"
echo "steam --> Open Steam"
echo "skype --> Open Skype"
echo "vlc --> Open VLC"
echo "term --> Open chroot terminal"
echo "off --> turn off screen but disable Standby when lid closed **USE WITH CAUTION**"
echo "on --> turn on screen and enable standby **Must type on and press enter to resume from "off" "
