#!/bin/bash
#Chromebook Script

#Download required scripts
cd ~/Downloads
wget https://github.com/dnschneid/crouton/raw/master/installer/crouton
wget https://github.com/dpeters1/CroutonConfig/raw/master/LinuxInstall
wget https://github.com/dpeters1/CroutonConfig/raw/master/bashrc
wget https://github.com/dpeters1/CroutonConfig/raw/master/Shortcuts

#Install chroot
sudo sh crouton -r trusty -t xiwi,core

sudo cp LinuxInstall /mnt/stateful_partition/crouton/chroots/trusty/bin

#Install other programs and configure chroot
sudo enter-chroot -l bash /bin/LinuxInstall

#Move files and clean up
mv bashrc ~/.bashrc
sudo mv Shortcuts ~/Shortcuts
rm -rf crouton
rm -rf Install
rm -rf LinuxInstall

#List command aliases
echo ""
echo "All Done"
echo ""
sh ~/Shortcuts
echo ""
cd /; exec bash
