#!/bin/bash
#Linux Script
sudo dpkg --add-architecture i386

#Spotify Pre-reqs
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D2C19886
echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
sudo apt-get update

#Download Steam and Skype
wget download.skype.com/linux/skype-ubuntu-precise_4.3.0.37-1_i386.deb
wget https://steamcommunity.com/linkfilter/http://media.steampowered.com/client/installer/steam.deb

#Install packages
sudo apt-get install spotify-client libpangoxft-1.0-0 pulseaudio gdebi-core vlc nano bash-completion

sudo gdebi skype-ubuntu-precise_4.3.0.37-1_i386.deb
sudo gdebi steam.deb

#Test whether spotify, skype, and linux were installed successfully
echo ""; echo "Successfully Installed:"; echo ""

dpkg --get-selections | grep -o "spotify\|steam\|skype"; echo "python 3.4"; echo "vlc"

echo ""; echo ""; echo ""