#!/bin/bash
#Lists shell aliases

echo "Shortcuts:"
echo "spotify --> Open Spotify"
echo "steam --> Open Steam"
echo "skype --> Open Skype"
echo "vlc --> Open VLC"
echo "term --> Open chroot terminal"
echo "off --> turn off screen but disable Standby when lid closed **USE WITH CAUTION**"
echo "on --> turn on screen and enable standby **Must type on and press enter to resume from "off" "
echo "root --> cd to root directory of chroot. cd chroot = cd mnt/stateful_partition/crouton/chroots/trusty" 
echo "shortcuts --> List Shortcuts"