#!/bin/bash
#Install arduino IDE
#Remove # to install adafruit-modified IDE

#wget https://s3.amazonaws.com/adafruit-download/adafruit-arduino-1.6.4-linux64.tar.xz
#tar xf adafruit-arduino-1.6.4-linux64.tar.xz -C ~/
#sudo apt-get -y install openjdk-7-jre
sudo apt-get -y install arduino arduino-core
#sudo adduser $USER dialout
#sudo adduser $USER serial